#!/usr/bin/env python3

import rospy
from sensor_msgs.msg import JointState

from markers import *
from lab6functions import *

if __name__ == '__main__':
    
 # Initialize the node
 rospy.init_node("testKineControlPose")
 print('starting motion ... ')
 # Publisher: publish to the joint_states topic
 pub = rospy.Publisher('joint_states', JointState, queue_size=1000)
 # Markers for the current and desired positions
 bmarker_current  = FrameMarker()
 bmarker_desired = FrameMarker(0.5)
 
 # Joint names
 jnames = ['shoulder_pan_joint', 'shoulder_lift_joint', 'elbow_joint', 'wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint']
 
 # Desired pose
 Rd = np.array([[1,0,0],[0,1,0],[0,0,1]])
 qd = Quaternion(matrix=Rd)
 # Find an xd that the robot can reach
 xd = np.array([0.3, 0.0, 0.3, qd.w, qd.x, qd.y, qd.z])
 # Initial configuration
 q0 = np.array([0.0, -1.0, 1.7, -2.2, -1.6, 0.0])
 
 # Resulting initial pose (end effector with respect to the base link)
 T = fkine(q0)
 x0 = TF2xyzquat(T)
 
 # Markers for the current and the desired pose
 bmarker_current.setPose(x0)
 bmarker_desired.setPose(xd)
 
 # Instance of the JointState message
 jstate = JointState()
 # Values of the message
 jstate.header.stamp = rospy.Time.now()
 jstate.name = jnames
 # Add the head joint value (with value 0) to the joints
 jstate.position = q0
 
 # Frequency (in Hz) and control period 
 freq = 50
 dt = 1.0/freq
 rate = rospy.Rate(freq)
 
 # Initial joint configuration
 q = copy(q0)
 x = copy(x0)
 quat = x[3:7]
 # Initialize the derror vector (derivative of the error)
 derror = np.zeros(7)
 # Main loop
 #for i in range(1):
 while not rospy.is_shutdown():
  # Current time (needed for ROS)
  jstate.header.stamp = rospy.Time.now()
  # Calculate the error between poses
  err_pose=PoseError(x,xd)

  # Kinematic control law for the pose (complete here)
  # --------------------------------------------------
  
  q = 
  
  # Current configuration trnaformation to current position
  T = fkine(q)
  x = TF2xyzquat(T)
  # Publish the message
  jstate.position = q
  pub.publish(jstate)
  bmarker_desired.setPose(xd)
  bmarker_current.setPose(x)
  # Wait for the next iteration
  rate.sleep()
